#Jake Eaton
#Introduction

import time
import sys

def type(string):
    for char in string:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(0.04)
    sys.stdout.write("\n")

def Intro():
    print("")
    type("You feel youself being dragged along the floor")
    time.sleep(2)
    type("You can't see... are you blindfolded? Or just blind?")
    time.sleep(2)
    type("You hear faint shouting as you as pulled up and sat down on a chair")
    time.sleep(2)
    type("The shouting gets louder as you begin to wake up")
    time.sleep(2)
    type("You suddenly sit bolt upright and realise that you have been chained to the chair")
    time.sleep(2)
    type("'Hello?!' you shout. No reply...")
    time.sleep(2)
    type("'Anyone?' Still no reply...")
    time.sleep(2)
    type("'I demand to know what I am doing here!' you call out. Now there was nothing but silence...")
    time.sleep(2)
    type("'All will be revealed.' said a woman's voice")
    time.sleep(2)
    type("The blindfold is removed from your eyes and you squint with the sudden light being shined in your face.")
    time.sleep(2)
    type("You try to look straight ahead and see a figure standing there")
    time.sleep(2)
    type("'What is your name?' the woman asked")
    name = input(">> ")
    type("'My name is "+name+"' you say")
    time.sleep(2)
    type("'Welcome to the Artemis "+name+". A science research station orbiting Jupiter.'")
    time.sleep(2)
    type("You manage to make out the slim figure of the dark haired woman and smile. You look around at the massive room and see two guards holding rifles on either side of you")
    time.sleep(2)
    type("'I have spent enough time in space. I'd quite like to go home thank you.' you say")
    time.sleep(2)
    type("'But you have nothing on Earth. Why go back?' she asked")
    time.sleep(2)
    type("She was right... since you lost your job, you have been alone, no family, no home...")
    time.sleep(2)
    type("'Because there I can forget about the past and move on with life. I have done my work to expand humanity into the stars. Why can't you just let me die in peace?' you reply.")
    time.sleep(2)
    type("'That is why you are here.' she says")
    time.sleep(2)
    type("You look at her, puzzled. She leans closer to you and whispers 'Your past.'")
    time.sleep(2)
    type("She stood up straight once again. 'Untie 'em' she says. You feel the chains loosen.")
    time.sleep(2)
    type("You leap on this advantage and drive your hand right into throat of one of the guards and took the gun from him")
    time.sleep(2)
    type("You point the gun at the other guard. The woman never moved as this happened")
    time.sleep(2)
    type("'Put the gun down!' shouted the guard. You don't move as the guard continues to tell you to put your gun down")
    time.sleep(2)
    type("'As you can see, you are no ordinary human' said the woman")
    time.sleep(2)
    type("'Somewhere in your past, something happened to you that changed your genetic makeup. It made you faster, stronger, smarter. But it also drove you insane.'")
    time.sleep(2)
    type("You look at the woman. 'We can help you.' she says.")
    time.sleep(2)
    type("You lower the gun and the other guard does the same. 'How will you help?' you ask")
    time.sleep(2)
    type("'We work for Admiral James Osbourne. He wants to know how you became like this. Then we will help reverse the effect and remove all traces of the event from your memory.' she says.")
    time.sleep(2)
    type("The name Osbourne was familiar to you but you couldn't think of why. 'What will it cost?' you ask.")
    time.sleep(2)
    type("'It will only cost your strength and willpower to relive memories until we find the right one' she walks over to you. 'We want to help you "+name+".'")
    time.sleep(2)
    type("You are tempted by this offer... but the name Osbourne still rings a bell...")
    time.sleep(2)
    type("You realise where and immediately react. You raise the gun and point it directly at the other guard and pull the trigger. Nothing...")
    time.sleep(2)
    type("You feel something hit your chest and you fall backwards... never feeling yourself land... 'You are so predictable' whispered a voice")
    time.sleep(2)
    type("You wake up to feel yourself lying down on something metal... a table? You try to move and realise your hands are spread out and they have been clamped down along with your legs")
    time.sleep(2)
    type("'What is this?' you call. This time you got an immediate answer")
    time.sleep(2)
    type("'This is the machine that will allow us to access your memories.' the same woman said.")
    time.sleep(2)
    type("'I will not give up my memories to a rebellion!' you protest.")
    time.sleep(2)
    type("'Well this 'rebellion' as you call it simply wants to create more like you so we can win the war against Earth.")
    time.sleep(2)
    type("The machine began to rotate you forward until you were upright. You hear the machine moving behind you and you suddenly feel very scared")
    time.sleep(2)
    type("'We are going to install a neural implant. Be warned. It is going to feel odd and may even be painful.'")
    time.sleep(2)
    type("'Wait a minute!' you protest. But it was too late. You feel something very small enter the back of your neck and you begin to cry out in pain.")
    time.sleep(2)
    type("You feel blood dripping down your neck and back as something entered the wound")
    time.sleep(2)
    type("'Please stop this!' you cry out. The woman didn't flinch as you feel something touch around your brain.")
    time.sleep(2)
    type("As quick as it started, the pain stopped. Blood continued to fall however.")
    time.sleep(2)
    type("'Prepare for us to enter your mind.' the woman turned around and began to walk away. 'Begin memory tap process!' she called.")
    time.sleep(2)
    type("You close you eyes and prepare for the worst. You hear screams, shouting, crying, laughing as you are flooded with memories")
    time.sleep(2)
    type("'Please stop!' you shout. But it didn't stop. Until...")
